<?php
return array(
    'domain' => 'http://localhost',
    'color_hexdec1' => '#000000',
    'color_hexdec2' => '#FFFFFF',
    'color_hexdec3' => '#FF0000',
    'color_hexdec4' => '#00FF00',
    'color_hexdec5' => '#0000FF',
    'color_hexdec6' => '#FFFF00',
    'color_hexdec7' => '#FF00FF',
    'color_hexdec8' => '#00FFFF',
    'color_label1' => '黒',
    'color_label2' => '白',
    'color_label3' => '赤',
    'color_label4' => '緑',
    'color_label5' => '青',
    'color_label6' => '黄色',
    'color_label7' => '紫',
    'color_label8' => '水色',
    'font1' => 'aplMincho.otf',
    'font2' => '03SmartFontUI.ttf',
    'font3' => 'SoukouMincho.ttf',
    'font4' => 'genkai-mincho.ttf',
    'font5' => 'ZakkuriGothic-BLK.otf',
    'font6' => 'Jiyucho.ttf',
    'font7' => 'f_feltpen04.otf',
    'font8' => 'GenEiGothicN-H-KL.otf',
    'font_label1' => 'アプリ明朝',
    'font_label2' => 'スマートフォント',
    'font_label3' => '装甲明朝',
    'font_label4' => '源界明朝',
    'font_label5' => 'ざっくりゴシック',
    'font_label6' => 'じゆうちょう',
    'font_label7' => 'フェルトフォント',
    'font_label8' => '源暎ゴシック',
);
